/** Token-based context-window styles embedded into the independently distributed client bundle. */
export const novelContextCss = String.raw`
.aiNovelContextTrigger{display:inline-flex;min-height:32px;align-items:center;gap:8px;border:0;border-radius:8px;padding:6px 10px;color:var(--dsw-alias-label-primary);background:transparent;cursor:pointer}
.aiNovelContextTrigger:hover,.aiNovelContextTrigger:focus-visible{background:var(--dsw-alias-interactive-bg-hover)}
.aiNovelWorkbenchFrameOpen{box-sizing:border-box;padding-right:440px}
.aiNovelContextOverlay{position:fixed;inset:0;z-index:2147483001;display:flex;justify-content:flex-end;pointer-events:none}
.aiNovelContextDrawer{box-sizing:border-box;width:440px;min-width:400px;max-width:calc(100vw - 80px);height:100%;overflow:auto;pointer-events:auto;border-left:1px solid var(--dsw-alias-border-inverted);padding:24px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-2);box-shadow:var(--dsw-shadow-lv3)}
.aiNovelContextOverlayV2,.aiNovelContextDrawerV2{min-width:0}
.aiNovelContextHeader,.aiNovelContextSectionHeader{display:flex;align-items:center;justify-content:space-between;gap:16px}
.aiNovelContextHeader h2,.aiNovelContextSections h3,.aiNovelContextSections h4,.aiNovelContextSections p,.aiNovelContextSetup h3,.aiNovelContextSetup p{margin:0}
.aiNovelContextBody,.aiNovelContextSetup{margin-top:24px}
.aiNovelContextSetup{border-top:1px solid var(--dsw-alias-border-l2);padding-top:20px}
.aiNovelContextSections{display:grid;gap:20px}
.aiNovelContextSections section{display:grid;gap:10px}
.aiNovelContextFacts{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:0}
.aiNovelContextFacts div{min-width:0}.aiNovelContextFacts dt{color:var(--dsw-alias-label-secondary)}.aiNovelContextFacts dd{margin:2px 0 0;overflow-wrap:anywhere}
.aiNovelContextCharacters{display:grid;gap:10px;margin:0;padding:0;list-style:none}.aiNovelContextCharacters li{display:grid;gap:4px}.aiNovelContextCharacters span,.aiNovelContextMuted{color:var(--dsw-alias-label-secondary)}
.aiNovelContextPreview{margin:0;max-height:320px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;font:inherit;color:inherit;background:var(--dsw-alias-bg-layer-1);border-radius:8px;padding:12px}
.aiNovelContextSectionHeader input{width:76px;min-height:32px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:4px 8px;color:inherit;background:transparent}
.aiNovelContextSrOnly{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.aiNovelPresetClose,.aiNovelPresetPrimary,.aiNovelPresetSecondary{min-height:32px;border-radius:8px;padding:6px 12px;cursor:pointer}
.aiNovelPresetClose,.aiNovelPresetSecondary{border:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-primary);background:transparent}
.aiNovelPresetPrimary{border:1px solid transparent;color:var(--dsw-alias-label-primary-foreground);background:var(--dsw-alias-button-primary-fill)}
.aiNovelPresetClose:focus-visible,.aiNovelPresetPrimary:focus-visible,.aiNovelPresetSecondary:focus-visible,.aiNovelBackButton:focus-visible,.aiNovelDangerButton:focus-visible,.aiNovelAssetList button:focus-visible,.aiNovelCharacterList button:focus-visible,.aiNovelWorkbenchField input:focus-visible,.aiNovelWorkbenchField select:focus-visible,.aiNovelWorkbenchField textarea:focus-visible,.aiNovelCastEditor input:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}
.aiNovelPresetPrimary:disabled{opacity:.45;cursor:default}
.aiNovelWorkbenchForm{display:grid;gap:16px}.aiNovelWorkbenchIntro{display:grid;gap:8px}.aiNovelWorkbenchIntro h3,.aiNovelWorkbenchIntro p{margin:0}
.aiNovelWorkbenchField{display:grid;gap:6px;font-size:13px;color:var(--dsw-alias-label-secondary)}
.aiNovelWorkbenchField input,.aiNovelWorkbenchField select,.aiNovelWorkbenchField textarea{box-sizing:border-box;width:100%;min-height:36px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:6px 10px;font:inherit;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-1)}.aiNovelWorkbenchField textarea{min-height:84px;resize:vertical}
.aiNovelWorkbenchField .aiNovelChapterDraftEditor{min-height:360px;line-height:1.65;overflow-wrap:anywhere;white-space:pre-wrap}
.aiNovelInitializationPreview{display:grid;gap:8px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:12px;background:var(--dsw-alias-bg-layer-1)}.aiNovelInitializationPreview h4,.aiNovelInitializationPreview p{margin:0}.aiNovelInitializationPreview pre{margin:0;max-height:240px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--dsw-alias-label-secondary)}
.aiNovelWorkbenchActions,.aiNovelPluginActions{display:flex;justify-content:flex-end;gap:8px}.aiNovelWorkbenchActions{position:sticky;bottom:-24px;margin:0 -24px -24px;padding:16px 24px;background:var(--dsw-alias-bg-layer-2);border-top:1px solid var(--dsw-alias-border-l2)}
.aiNovelWorkbenchActionsInline{position:static;margin:0;padding:0;border:0}.aiNovelWorkbenchActions button:disabled,.aiNovelCharacterToolbar button:disabled{opacity:.45;cursor:default}
.aiNovelAssetList{display:grid;gap:8px}.aiNovelAssetList button,.aiNovelCharacterList button{display:grid;gap:3px;width:100%;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:10px 12px;text-align:left;font:inherit;color:inherit;background:var(--dsw-alias-bg-layer-1);cursor:pointer}.aiNovelAssetList button:hover,.aiNovelCharacterList button:hover,.aiNovelCharacterList button[aria-current=true]{background:var(--dsw-alias-interactive-bg-hover)}.aiNovelAssetList span,.aiNovelCharacterList span{font-size:12px;color:var(--dsw-alias-label-secondary)}
.aiNovelAssetHeading{display:grid;gap:12px}.aiNovelAssetHeading h3,.aiNovelAssetHeading p{margin:0}.aiNovelAssetHeading p{margin-top:3px;font-size:12px;color:var(--dsw-alias-label-tertiary);overflow-wrap:anywhere}.aiNovelBackButton{display:inline-flex;justify-self:start;min-height:34px;align-items:center;gap:7px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:6px 10px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-1);font:inherit;font-weight:500;cursor:pointer}.aiNovelBackButton:hover{background:var(--dsw-alias-interactive-bg-hover)}.aiNovelBackButton:disabled{opacity:.45;cursor:default}
.aiNovelGenerationPanel{display:grid;gap:10px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;padding:12px;background:var(--dsw-alias-bg-layer-1)}.aiNovelGenerationHeader{display:grid;gap:4px}.aiNovelGenerationHeader h4,.aiNovelGenerationHeader p,.aiNovelGenerationPanel>p{margin:0}.aiNovelGenerationHeader p{font-size:12px;color:var(--dsw-alias-label-secondary)}.aiNovelGenerationButton{justify-self:start}
.aiNovelCharacterToolbar{display:grid;grid-template-columns:1fr auto;align-items:end;gap:8px}.aiNovelCharacterList{display:grid;gap:6px;max-height:210px;overflow:auto;margin:0;padding:0;list-style:none}.aiNovelCharacterEditor{display:grid;gap:12px;margin:0;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:12px}.aiNovelCharacterEditor legend{padding:0 5px;color:var(--dsw-alias-label-secondary)}
.aiNovelRelationshipEditor,.aiNovelCastEditor{display:grid;gap:10px;margin:0;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:10px}.aiNovelRelationshipEditor legend,.aiNovelCastEditor legend{padding:0 5px;color:var(--dsw-alias-label-secondary)}.aiNovelRelationshipRow{display:grid;gap:8px;border-bottom:1px solid var(--dsw-alias-border-l2);padding-bottom:10px}.aiNovelRelationshipRow>button,.aiNovelRelationshipEditor>button{justify-self:start}.aiNovelCastEditor>label{display:flex;align-items:center;gap:8px;min-height:30px;color:var(--dsw-alias-label-primary)}.aiNovelCastEditor input{width:16px;height:16px;margin:0;accent-color:var(--dsw-alias-brand-primary)}
.aiNovelDangerButton{justify-self:start;min-height:32px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:6px 10px;color:var(--dsw-alias-state-error-primary);background:transparent;cursor:pointer}.aiNovelEditorNotice{display:grid;gap:8px;border-left:2px solid var(--dsw-alias-brand-primary);padding-left:10px}.aiNovelEditorNotice p{margin:0}
.aiNovelPluginCard{list-style:none;border:1px solid var(--dsw-alias-border-l2);border-radius:12px;padding:16px;background:var(--dsw-alias-bg-layer-3)}
.aiNovelPluginCardHeader{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.aiNovelPluginCardHeader strong{font-size:15px}.aiNovelPluginCardHeader p{margin:4px 0 0;color:var(--dsw-alias-label-tertiary);font-size:13px}
.aiNovelPluginMounted{flex:none;border-radius:999px;padding:2px 8px;color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-bg-module-platform);font-size:11px}
.aiNovelPluginFacts{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:16px 0}.aiNovelPluginFacts div{min-width:0}.aiNovelPluginFacts dt{font-size:12px;color:var(--dsw-alias-label-tertiary)}.aiNovelPluginFacts dd{margin:2px 0 0;font-size:13px;color:var(--dsw-alias-label-primary)}
.aiNovelV2Workbench{display:grid;gap:20px;min-width:0}.aiNovelV2Panel{display:grid;gap:10px;min-width:0}.aiNovelV2Panel h3,.aiNovelV2Panel p{margin:0}.aiNovelV2Summary{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:0}.aiNovelV2Summary div{min-width:0}.aiNovelV2Summary dt{font-size:12px;color:var(--dsw-alias-label-tertiary)}.aiNovelV2Summary dd{margin:2px 0 0;overflow-wrap:anywhere}.aiNovelV2List{display:grid;gap:6px;margin:0;padding:0;list-style:none}.aiNovelV2List button,.aiNovelV2DetailList button,.aiNovelV2AssetNav button{width:100%;min-height:36px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:7px 10px;text-align:left;font:inherit;color:inherit;background:var(--dsw-alias-bg-layer-1);cursor:pointer}.aiNovelV2List button[aria-current=true],.aiNovelV2List button:hover,.aiNovelV2DetailList button:hover,.aiNovelV2AssetNav button:hover{background:var(--dsw-alias-interactive-bg-hover)}.aiNovelV2DetailList,.aiNovelV2AssetNav,.aiNovelV2Diff{display:grid;gap:8px;min-width:0}.aiNovelV2DetailList>div,.aiNovelV2CommandDiff,.aiNovelV2CommandDiff section,.aiNovelV2Diff section{min-width:0}.aiNovelV2CommandDiff dd{overflow-wrap:anywhere}.aiNovelV2CommandDiff h4,.aiNovelV2Diff h4{margin:0;font-size:13px}.aiNovelV2CommandDiff pre,.aiNovelV2Diff pre{margin:0;max-width:100%;max-height:240px;overflow:auto;overflow-wrap:anywhere;white-space:pre-wrap;font:12px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace}.aiNovelV2Editor textarea{width:100%;min-height:360px;box-sizing:border-box;resize:vertical;overflow:auto;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:10px;font:12px/1.6 ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-1)}
.aiNovelV2Authoring{display:grid;gap:10px}.aiNovelV2Authoring h4{margin:0}.aiNovelV2Authoring .aiNovelV2Brief{min-height:84px;font:inherit;line-height:1.5}.aiNovelV2Authoring .aiNovelV2ManualDraft{min-height:260px}
.aiNovelV2StructuredFields{display:grid;gap:10px;margin:0;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:10px}.aiNovelV2StructuredFields legend{padding:0 5px;color:var(--dsw-alias-label-secondary)}.aiNovelV2StructuredFields textarea{min-height:96px;font:inherit;line-height:1.5}
.aiNovelV2StageShell{display:grid;grid-template-columns:minmax(0,1fr);gap:16px;align-items:start;min-width:0}.aiNovelV2StageNav,.aiNovelV2StageContent{display:grid;gap:12px;min-width:0}.aiNovelV2StageNav h3,.aiNovelV2StageNav p,.aiNovelV2StageEmpty h3,.aiNovelV2StageEmpty p{margin:0}.aiNovelV2StageEmpty{display:grid;gap:8px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;padding:14px;background:var(--dsw-alias-bg-layer-1)}.aiNovelV2AssetNav{grid-template-columns:repeat(auto-fit,minmax(148px,1fr))}.aiNovelV2AssetNav button[aria-current=true]{background:var(--dsw-alias-interactive-bg-hover);border-color:var(--dsw-alias-border-l2)}.aiNovelV2Review{display:grid;gap:10px;min-width:0;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;padding:12px;background:var(--dsw-alias-bg-layer-1)}.aiNovelV2Review[data-ai-novel-proposal-dock]{align-self:stretch}.aiNovelV2Review summary{min-height:30px;cursor:pointer;font-weight:600;color:var(--dsw-alias-label-primary)}.aiNovelV2ReviewBody{display:grid;gap:16px;min-width:0;padding-top:2px}.aiNovelV2AuthoringActions,.aiNovelV2ReviewActions{display:flex;flex-wrap:wrap;align-items:center;justify-content:flex-start;gap:8px;position:static;margin:0;padding:0;border:0;background:transparent}.aiNovelV2AuthoringActions button,.aiNovelV2ReviewActions button{min-height:36px}
@media(min-width:1360px){.aiNovelWorkbenchFrameOpenV2{padding-right:calc(100vw - 386px)}.aiNovelContextOverlayV2{left:386px}.aiNovelContextDrawerV2{width:100%;min-width:0;max-width:none}.aiNovelContextDrawerV2 .aiNovelV2StructuredFields{grid-template-columns:repeat(2,minmax(0,1fr))}.aiNovelContextDrawerV2 .aiNovelV2StructuredFields legend,.aiNovelContextDrawerV2 .aiNovelV2StructuredFieldWide{grid-column:1/-1}.aiNovelContextDrawerV2 .aiNovelV2WorkbenchForm .aiNovelV2Panel{grid-template-columns:repeat(2,minmax(0,1fr))}.aiNovelContextDrawerV2 .aiNovelV2WorkbenchForm .aiNovelV2Panel>h3,.aiNovelContextDrawerV2 .aiNovelV2WorkbenchForm .aiNovelV2Panel>p,.aiNovelContextDrawerV2 .aiNovelV2WorkbenchForm .aiNovelWorkbenchActions{grid-column:1/-1}}
@media(min-width:1024px) and (max-width:1359px){.aiNovelWorkbenchFrameOpenV2{padding-right:calc(100vw - 56px)}.aiNovelContextOverlayV2{left:56px}.aiNovelContextDrawerV2{width:100%;min-width:0;max-width:none}}
@media(max-width:1023px){.aiNovelWorkbenchFrameOpenV2{padding-right:calc(100vw - 56px)}.aiNovelContextOverlayV2{left:56px}.aiNovelContextDrawerV2{width:100%;min-width:0;max-width:none}.aiNovelV2StageShell,.aiNovelV2AssetNav{grid-template-columns:1fr}}
@media(max-width:899px){.aiNovelWorkbenchFrameOpen:not(.aiNovelWorkbenchFrameOpenV2){padding-right:0}.aiNovelContextDrawer{width:100%;min-width:0;max-width:none;padding:18px}.aiNovelContextFacts,.aiNovelPluginFacts,.aiNovelV2Summary{grid-template-columns:1fr}.aiNovelWorkbenchActions{bottom:-18px;margin:0 -18px -18px;padding:14px 18px}.aiNovelV2StageShell{grid-template-columns:minmax(0,1fr);gap:14px}.aiNovelV2StageNav{order:0}.aiNovelV2StageContent{order:1}.aiNovelV2Review{order:2}}
@media(max-width:520px){.aiNovelV2AssetNav{grid-template-columns:1fr}.aiNovelV2AuthoringActions,.aiNovelV2ReviewActions{align-items:stretch}.aiNovelV2AuthoringActions button,.aiNovelV2ReviewActions button{width:100%}}
`

/**
 * Install this plugin's context-window styles for one client fiber.
 *
 * @param target Browser document receiving the owned style element.
 * @returns A disposer that removes only this plugin's style element.
 */
export function installNovelContextStyle(target: Document): () => void {
  const style = target.createElement('style')
  style.dataset.plugin = '@ethanyoq/dsh-ai-novel-writer'
  style.dataset.pluginCss = '@ethanyoq/dsh-ai-novel-writer/context-window'
  style.textContent = novelContextCss
  target.head.appendChild(style)
  return () => { style.remove() }
}
